# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68cc225401d4b07b100ee4a3e9b8645f7f38f5f82cdcf7765af80c1eeba8dfb283bba33abec572f7989ed68d4016960a3de656cac8726f9c55704a4cb164dddd

test:
  secret_key_base: 86d35160b708a87d494ee6217aed98b4a0e9cace98ab41ff2f34ea1e32117ae538d1812dad46f8013e92cdfa8deb07407cb18d8b2bb84648b180df1f84d57343

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
